name: 'Easy Cloud Run - vpcsql'
description: 'Create a Cloud SQL instance in a VPC, deploy a Cloud Run service connected to that database'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/../vpcsql.sh
      shell: bash
